"""
Sou Model Format
Defines the .sou model configuration format (Ollama-inspired).
"""

from dataclasses import dataclass
from typing import Optional, List, Dict, Any


@dataclass
class GenerationParameters:
    """Generation parameters."""

    temperature: float = 0.7
    top_p: float = 0.9
    top_k: int = 40
    max_tokens: int = 2048
    stop: List[str] = None

    def __post_init__(self):
        if self.stop is None:
            self.stop = []


@dataclass
class ContextParameters:
    """Context parameters."""

    context_window: int = 4096
    num_ctx: int = 4096
    num_gpu: int = 0


@dataclass
class PersonalityConfig:
    """Personality configuration."""

    warmth: float = 0.5
    creativity: float = 0.5
    empathy: float = 0.5
    formality: float = 0.5
    humor: float = 0.5
    patience: float = 0.5
    confidence: float = 0.5

    def to_dict(self) -> Dict[str, float]:
        return {
            "warmth": self.warmth,
            "creativity": self.creativity,
            "empathy": self.empathy,
            "formality": self.formality,
            "humor": self.humor,
            "patience": self.patience,
            "confidence": self.confidence,
        }


@dataclass
class ACLConfig:
    """Access control configuration."""

    allowed_users: List[str] = None
    rate_limit: Optional[int] = None
    max_requests_per_minute: int = 60

    def __post_init__(self):
        if self.allowed_users is None:
            self.allowed_users = []


@dataclass
class WatermarkConfig:
    """Watermark configuration."""

    enabled: bool = False
    strength: float = 0.1
    text: str = "Generated by SloughGPT"


class QuantizationType:
    """Quantization types."""

    NONE = "none"
    Q4_0 = "q4_0"
    Q4_1 = "q4_1"
    Q5_0 = "q5_0"
    Q5_1 = "q5_1"
    Q8_0 = "q8_0"


@dataclass
class SouModelFile:
    """Sou model file configuration."""

    from_model: str
    parameters: GenerationParameters = None
    context: ContextParameters = None
    system: str = "You are a helpful AI assistant."
    personality: PersonalityConfig = None
    acl: ACLConfig = None
    watermark: WatermarkConfig = None
    metadata: Dict[str, str] = None

    def __post_init__(self):
        if self.parameters is None:
            self.parameters = GenerationParameters()
        if self.context is None:
            self.context = ContextParameters()
        if self.personality is None:
            self.personality = PersonalityConfig()
        if self.acl is None:
            self.acl = ACLConfig()
        if self.watermark is None:
            self.watermark = WatermarkConfig()
        if self.metadata is None:
            self.metadata = {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "from_model": self.from_model,
            "parameters": {
                "temperature": self.parameters.temperature,
                "top_p": self.parameters.top_p,
                "top_k": self.parameters.top_k,
                "max_tokens": self.parameters.max_tokens,
            },
            "context": {
                "context_window": self.context.context_window,
                "num_ctx": self.context.num_ctx,
                "num_gpu": self.context.num_gpu,
            },
            "system": self.system,
            "personality": self.personality.to_dict(),
            "watermark": {
                "enabled": self.watermark.enabled,
                "strength": self.watermark.strength,
            },
            "metadata": self.metadata,
        }

    def to_sou_string(self) -> str:
        """Convert to .sou file format string."""
        lines = [
            f"FROM {self.from_model}",
            "",
            "PARAMETER",
            f"    temperature {self.parameters.temperature}",
            f"    top_p {self.parameters.top_p}",
            f"    top_k {self.parameters.top_k}",
            f"    max_tokens {self.parameters.max_tokens}",
            "",
        ]

        if self.personality:
            lines.extend(
                [
                    "PERSONALITY",
                    f"    warmth {self.personality.warmth}",
                    f"    creativity {self.personality.creativity}",
                    f"    empathy {self.personality.empathy}",
                    f"    formality {self.personality.formality}",
                    "    END",
                    "",
                ]
            )

        if self.system:
            lines.append(f"SYSTEM {self.system}")
            lines.append("")

        if self.metadata:
            for key, value in self.metadata.items():
                lines.append(f'METADATA {key} "{value}"')
            lines.append("")

        return "\n".join(lines)


class SouParser:
    """Parser for .sou model files."""

    @staticmethod
    def parse(content: str) -> SouModelFile:
        """Parse .sou content into SouModelFile."""
        lines = content.strip().split("\n")

        from_model = ""
        params = GenerationParameters()
        ctx = ContextParameters()
        personality = PersonalityConfig()
        system = ""
        metadata = {}

        current_section = None

        for line in lines:
            line = line.strip()

            if not line or line.startswith("#"):
                continue

            if line.startswith("FROM "):
                from_model = line[5:].strip()
            elif line.startswith("PARAMETER"):
                current_section = "parameter"
            elif line.startswith("PERSONALITY"):
                current_section = "personality"
            elif line.startswith("SYSTEM "):
                system = line[7:].strip()
            elif line.startswith("METADATA "):
                key, value = line[9:].split(" ", 1)
                metadata[key] = value.strip('"')
            elif line == "END":
                current_section = None
            elif current_section == "parameter":
                if line.startswith("temperature "):
                    params.temperature = float(line.split()[1])
                elif line.startswith("top_p "):
                    params.top_p = float(line.split()[1])
                elif line.startswith("top_k "):
                    params.top_k = int(line.split()[1])
                elif line.startswith("max_tokens "):
                    params.max_tokens = int(line.split()[1])
            elif current_section == "personality":
                if line.startswith("warmth "):
                    personality.warmth = float(line.split()[1])
                elif line.startswith("creativity "):
                    personality.creativity = float(line.split()[1])
                elif line.startswith("empathy "):
                    personality.empathy = float(line.split()[1])
                elif line.startswith("formality "):
                    personality.formality = float(line.split()[1])

        return SouModelFile(
            from_model=from_model,
            parameters=params,
            context=ctx,
            system=system,
            personality=personality,
            metadata=metadata,
        )

    @staticmethod
    def load(path: str) -> SouModelFile:
        """Load .sou file from path."""
        with open(path, "r") as f:
            content = f.read()
        return SouParser.parse(content)

    @staticmethod
    def save(sou: SouModelFile, path: str):
        """Save SouModelFile to path."""
        with open(path, "w") as f:
            f.write(sou.to_sou_string())


def create_default_sou(
    model_name: str,
    temperature: float = 0.7,
    personality: Optional[PersonalityConfig] = None,
) -> SouModelFile:
    """Create default .sou configuration."""
    return SouModelFile(
        from_model=model_name,
        parameters=GenerationParameters(temperature=temperature),
        personality=personality or PersonalityConfig(),
    )
